name: Gemini-O1 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pylint
        
    - name: Lint with pylint
      run: |
        pylint --disable=C0111,C0103,C0303,C0330,C0326 gemini_o1/ || true
        
    - name: Test with pytest
      env:
        PYTEST_CURRENT_TEST: 1
      run: |
        pytest --cov=gemini_o1 --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx_rtd_theme
        
    - name: Build documentation
      run: |
        mkdir -p docs
        sphinx-quickstart -q -p "Gemini-O1" -a "Contributors" -v "0.1" docs
        cd docs
        sphinx-build -b html . _build/html || true